version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: toby
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  server:
    build: ./server
    environment:
      DATABASE_URL: postgres://postgres:password@postgres:5432/toby
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    volumes:
      - ./server:/app
      - /app/node_modules

volumes:
  postgres-data:
